services:

  postgres:
    image: postgres:17
    container_name: artifact-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: artifact_user
      POSTGRES_PASSWORD: artifact_password
      POSTGRES_DB: artifact_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: